##################################################
services:
 # magicmirror:
 #   container_name: magic_mirror
 #   image: karsten13/magicmirror:latest
 #   restart: no
 #   user: root
 #   volumes:
 #     - ../home_server/config/magic_mirror/config:/opt/magic_mirror/config
 #     - ../home_server/config/magic_mirror/modules:/opt/magic_mirror/modules
 #     - ../home_server/config/magic_mirror/css:/opt/magic_mirror/css
 #   ports:
 #     - 8080:8080

##################################################
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie_home
    restart: no
    volumes:
      - mealie_data:/app/data
      - ../home_server/config/mealie:/home_server/config/mealie
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      BASE_URL: 192.168.0.250
      DEFAULT_EMAIL: blubaughj@gmail.com
      DEFAULT_GROUP: group
      DEFAULT_HOUSEHOLD: blubaugh

##################################################
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - heimdall_data:/config
      - ../home_server/config/heimdall:/home_server/config/heimdall
    ports:
      - 8006:80
      - 406:443
    restart: no

##################################################
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      # Plain DNS
      - '5300:53/tcp'
      - '5300:53/udp'
      # AdGuard Home Admin Panel as well as DNS-over-HTTPS
      - '80:80/tcp'
      - '443:443/tcp'
      - '443:443/udp'
      - '3000:3000/tcp'
      # DNS-over-TLS
      - '853:853/tcp'
      # DNS-over-QUIC
      - '784:784/udp'
      - '853:853/udp'
      - '8853:8853/udp'
      # DNSCrypt
      - '5443:5443/tcp'
      - '5443:5443/udp'
    volumes:
      - adguard_data:/opt/homeserver/adguardhome
      - ../home_server/config/adguard:/home_server/config/adguard

##################################################
volumes:
  mealie_data:
  heimdall_data:
  adguard_data: